# Build an example Docker container image.
FROM busybox
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"
LABEL maintainer="Jeff Geerling"

# Run a command when the container starts.
CMD ["/bin/true"]
