# Build a simple MySQL data volume Docker container.
FROM busybox
LABEL maintainer="Nho Luong <luongutnho@hotmail.com>"

# Create data volume for MySQL.
RUN mkdir -p /var/lib/mysql
VOLUME /var/lib/mysql
