---
roles:
- name: nholuongut.java
- name: nholuongut.nginx
- name: nholuongut.pip
- name: nholuongut.elasticsearch
  version: 5.0.0
- name: nholuongut.elasticsearch-curator
  version: 2.1.0
- name: nholuongut.kibana
  version: 4.0.0
- name: nholuongut.logstash
  version: 5.1.0
- name: nholuongut.filebeat
  version: 3.0.1
