---
- hosts: lamp_varnish
  become: yes

  vars_files:
    - vars.yml

  roles:
    - nholuongut.firewall
    - nholuongut.repo-epel
    - nholuongut.varnish

  tasks:
    - name: Copy Varnish default.vcl.
      template:
        src: "templates/default.vcl.j2"
        dest: "/etc/varnish/default.vcl"
      notify: restart varnish
